[package]
name = "geoconv"
version = "0.1.0"
authors = ["Tokarev Artyom <tokarev28.art@gmail.com>"]
edition = "2021"

[dependencies]
nalgebra = "0.21"
fnv = "1.0"
indexmap = "1.8.1"
by_addr = { git = "https://github.com/tokarevart/by_addr" }
